language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#webplatform-bot"
    template:
      - "%{repository}#%{build_number} (on %{branch} by %{author}): %{message} %{build_url}"
